[project]
name = "merge-table-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.30.1",
    "openai>=1.107.2",
    "pydantic>=2.11.9",
    "pymupdf>=1.26.4",
]
